---
services:

  ############################################################
  # backup_raid
  ############################################################

  backup_raid:
    image: docker-hosted.proxy-int.pendragonlab.com/elise/grail:main
    entrypoint: python src

    profiles:
      - backup-raid

    environment:
      - TZ=America/Denver
      - BACKUP_OBJECT=${BACKUP_OBJECT}
      - BACKUP_DISK=${BACKUP_DISK}1
      - DISK_PASSWORD=${DISK_PASSWORD}
      - DISK_MOUNTPOINT=/grail-dst
      - VAULT_ENDPOINT=${VAULT_ENDPOINT}
      - SMB_SHARE_HOST=${SMB_SHARE_HOST}
      - SMB_SHARE_NAME=${SMB_SHARE_NAME}
      - SMB_SHARE_UID=${SMB_SHARE_UID}
      - SMB_SHARE_GID=${SMB_SHARE_GID}
      - SMB_APPROLE=${SMB_APPROLE}
      - SMB_VAULT_PATH=${SMB_VAULT_PATH}

    devices:
      - ${BACKUP_DISK}

    volumes:
      - type: volume
        source: raid_vol
        target: /grail-src
        read_only: false

    networks:
      - grail

    logging:
      options:
        max-size: 10m
        max-file: '10'

  ############################################################
  # restore_raid
  ############################################################

  restore_raid:
    image: docker-hosted.proxy-int.pendragonlab.com/elise/grail:main
    entrypoint: python src

    profiles:
      - restore-raid

    environment:
      - TZ=America/Denver
      - BACKUP_OBJECT=${BACKUP_OBJECT}
      - BACKUP_DISK=${BACKUP_DISK}1
      - DISK_PASSWORD=${DISK_PASSWORD}
      - DISK_MOUNTPOINT=/grail-src
      - VAULT_ENDPOINT=${VAULT_ENDPOINT}
      - SMB_SHARE_HOST=${SMB_SHARE_HOST}
      - SMB_SHARE_NAME=${SMB_SHARE_NAME}
      - SMB_SHARE_UID=${SMB_SHARE_UID}
      - SMB_SHARE_GID=${SMB_SHARE_GID}
      - SMB_APPROLE=${SMB_APPROLE}
      - SMB_VAULT_PATH=${SMB_VAULT_PATH}

    devices:
      - ${BACKUP_DISK}

    volumes:
      - type: volume
        source: raid_vol
        target: /dst-backup-path
        read_only: false

    networks:
      - grail

    logging:
      options:
        max-size: 10m
        max-file: '10'

  ############################################################
  # backup_app
  ############################################################

  backup_app:
    image: docker-hosted.proxy-int.pendragonlab.com/elise/grail:main
    entrypoint: python src

    profiles:
      - backup-app

    environment:
      - TZ=America/Denver
      - BACKUP_OBJECT=app
      - BACKUP_DISK=${BACKUP_DISK}1
      - DISK_PASSWORD=${DISK_PASSWORD}
      - DISK_MOUNTPOINT=/grail-dst

    devices:
      - ${BACKUP_DISK}

    volumes:
      - type: bind
        source: /mnt/dfs_lvm/lab_dfs
        target: /src-backup-path
        read_only: false

    networks:
      - grail

    logging:
      options:
        max-size: 10m
        max-file: '10'

  ############################################################
  # restore_app
  ############################################################

  restore_app:
    image: docker-hosted.proxy-int.pendragonlab.com/elise/grail:main
    entrypoint: python src

    profiles:
      - restore-app

    environment:
      - TZ=America/Denver
      - BACKUP_OBJECT=app
      - BACKUP_DISK=${BACKUP_DISK}1
      - DISK_PASSWORD=${DISK_PASSWORD}
      - DISK_MOUNTPOINT=/grail-src

    devices:
      - ${BACKUP_DISK}

    volumes:
      - type: bind
        source: /mnt/dfs_lvm/lab_dfs
        target: /grail-dst
        read_only: false

    networks:
      - grail

    logging:
      options:
        max-size: 10m
        max-file: '10'

###########################################################
# resources
###########################################################

volumes:
  raid_root_share:
    driver_opts:
      type: cifs
      o: "\
        username=${RAID_ROOT_SHARE_USERNAME},\
        password=${RAID_ROOT_SHARE_PASSWORD},\
        uid=${RAID_ROOT_SHARE_UID},\
        gid=${RAID_ROOT_SHARE_GID},\
        dir_mode=0770,\
        file_mode=0770,\
        iocharset=utf8"
      device: //${RAID_ROOT_SHARE_HOST}/${RAID_ROOT_SHARE_NAME}

networks:
  grail:
    name: grail
