---
services:

  ############################################################
  # backup_raidvol
  ############################################################

  backup_raidvol:
    image: docker-hosted.proxy-int.pendragonlab.com/elise/grail:main
    entrypoint: python src

    profiles:
      - backup-raidvol

    environment:
      - TZ=America/Denver
      - BACKUP_OBJECT=${BACKUP_OBJECT}
      - BACKUP_DISK=${BACKUP_DISK}
      - DISK_PASSWORD=${DISK_PASSWORD}
      - DISK_MOUNTPOINT=/grail-dst

    devices:
      - ${BACKUP_DISK}

    volumes:
      - type: volume
        source: raid_vol
        target: /grail-src
        read_only: false

    networks:
      - grail

    logging:
      options:
        max-size: 10m
        max-file: '10'

  ############################################################
  # restore_raidvol
  ############################################################

  restore_raidvol:
    image: docker-hosted.proxy-int.pendragonlab.com/elise/grail:main
    entrypoint: python src

    profiles:
      - restore-raidvol

    environment:
      - TZ=America/Denver
      - BACKUP_OBJECT=${BACKUP_OBJECT}
      - BACKUP_DISK=${BACKUP_DISK}
      - DISK_PASSWORD=${DISK_PASSWORD}
      - DISK_MOUNTPOINT=/grail-src

    devices:
      - ${BACKUP_DISK}

    volumes:
      - type: volume
        source: raid_vol
        target: /dst-backup-path
        read_only: false

    networks:
      - grail

    logging:
      options:
        max-size: 10m
        max-file: '10'

  ############################################################
  # backup_appvol
  ############################################################

  backup_appvol:
    image: docker-hosted.proxy-int.pendragonlab.com/elise/grail:main
    entrypoint: python src

    profiles:
      - backup-appvol

    environment:
      - TZ=America/Denver
      - BACKUP_OBJECT=labvol

    volumes:
      - type: bind
        source: /mnt/dfs_lvm/lab_dfs
        target: /src-backup-path
        read_only: false

      - type: bind
        source: /mnt/usb-backup/labvol
        target: /dst-backup-path
        read_only: false

    networks:
      - grail

    logging:
      options:
        max-size: 10m
        max-file: '10'

  ############################################################
  # restore_appvol
  ############################################################

  restore_appvol:
    image: docker-hosted.proxy-int.pendragonlab.com/elise/grail:main
    entrypoint: python src

    profiles:
      - restore-appvol

    environment:
      - TZ=America/Denver
      - BACKUP_OBJECT=labvol

    volumes:
      - type: bind
        source: /mnt/usb-backup/labvol
        target: /src-backup-path
        read_only: false

      - type: bind
        source: /mnt/dfs_lvm/lab_dfs
        target: /grail-dst
        read_only: false

    networks:
      - grail

    logging:
      options:
        max-size: 10m
        max-file: '10'

###########################################################
# resources
###########################################################

volumes:
  raidvol_root_share:
    driver_opts:
      type: cifs
      o: "\
        username=${RAIDVOL_ROOT_SHARE_USERNAME},\
        password=${RAIDVOL_ROOT_SHARE_PASSWORD},\
        uid=${RAIDVOL_ROOT_SHARE_UID},\
        gid=${RAIDVOL_ROOT_SHARE_GID},\
        dir_mode=0770,\
        file_mode=0770,\
        iocharset=utf8"
      device: //${RAIDVOL_ROOT_SHARE_HOST}/${RAIDVOL_ROOT_SHARE_NAME}

networks:
  grail:
    name: grail
