---
services:

  ############################################################
  # cli
  ############################################################

  cli:
    image: docker-hosted.proxy-int.pendragonlab.com/elise/grail:main
    entrypoint: python src
    profiles:
      - cli

    environment:
      - TZ=America/Denver
      - BACKUP_OBJECT=${BACKUP_OBJECT}
      - BACKUP_MODE=${BACKUP_MODE}

    volumes:
      - type: bind
        source: ${BACKUP_SRC_PATH}
        target: /src-backup-path
        read_only: false

      - type: bind
        source: ${BACKUP_DST_PATH}
        target: /dst-backup-path
        read_only: false

    networks:
      - grail

###########################################################
# resources
###########################################################

networks:
  grail:
    name: grail
